services:
  db:
    image: postgres:16-alpine # Using a lightweight Alpine-based Postgres image
    container_name: blog_postgres_db
    restart: always # Ensure the container restarts if it crashes
    ports:
      - "5432:5432" # Map host port 5432 to container port 5432
    environment:
      POSTGRES_DB: blogdb # Database name
      POSTGRES_USER: your_username # Database user (match appsettings.json)
      POSTGRES_PASSWORD: your_password # Database password (match appsettings.json)
    volumes:
      - pgdata:/var/lib/postgresql/data # Persist data to a named volume
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  pgdata: # Define the named volume for data persistence