global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s
alerting:
  alertmanagers:
    - static_configs:
        - targets: []
      scheme: http
      timeout: 10s
      api_version: v1
scrape_configs:
  - job_name: prometheus
    honor_timestamps: true
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets:
          - localhost:9090
  - job_name: test-api-app-metrics
    metrics_path: /metrics-text
    static_configs:
      - targets: ["host.docker.internal:5000"] 
  - job_name: test-api-otel-metrics
    metrics_path: /metrics-text-2
    static_configs:
      - targets: ["host.docker.internal:5000"]
