version: "3"

services:
  zipkin:
    image: openzipkin/zipkin
    hostname: zipkin
    container_name: zipkin
    ports:
      - "9411:9411"
  seq:
    image: "datalust/seq:2021"
    hostname: seq
    container_name: seq
    ports:
      - "5341:5341" # ingestion API
      - "5555:80" # ui
    environment:
      ACCEPT_EULA: "Y"
