version: "3.2"
services:
  rabbitmq:
    restart: always
    image: masstransit/rabbitmq
    container_name: 'rabbitmq'
    ports:
      - 5672:5672
      - 15672:15672
  seq:
    container_name: seq
    restart: always
    environment:
      - ACCEPT_EULA=Y
    image: datalust/seq
    ports:
      - "5555:80"
      - "5341:5341"
    volumes:
      - seq:/data
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local  
  seq:
    driver: local
