name: TUnit Tests

on:
  workflow_dispatch:
    inputs:
      run_playwright:
        description: 'Run Playwright tests'
        required: false
        type: boolean
        default: false

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'

      - name: Restore dependencies
        run: dotnet restore TUnitTesting.sln
        working-directory: src/Testing/TUnit

      - name: Build
        run: dotnet build TUnitTesting.sln --no-restore -c Release
        working-directory: src/Testing/TUnit

      - name: Run unit and integration tests
        if: ${{ !inputs.run_playwright }}
        working-directory: src/Testing/TUnit
        run: |
          dotnet test --project TUnitTesting.UnitTests/TUnitTesting.UnitTests.csproj --no-build -c Release --verbosity normal
          dotnet test --project TUnitTesting.IntegrationTests/TUnitTesting.IntegrationTests.csproj --no-build -c Release --verbosity normal

      - name: Install Playwright Browsers
        if: ${{ inputs.run_playwright }}
        working-directory: src/Testing/TUnit
        run: pwsh TUnitTesting.PlaywrightTests/bin/Release/net10.0/playwright.ps1 install --with-deps chromium

      - name: Run Playwright tests
        if: ${{ inputs.run_playwright }}
        working-directory: src/Testing/TUnit
        run: |
          dotnet test --project TUnitTesting.PlaywrightTests/TUnitTesting.PlaywrightTests.csproj --no-build -c Release --verbosity normal
